<?php
/**
 * @file
 * Sends Webform results to HubSpot's Forms API.
 */

use Drupal\Component\Serialization\Json;
use Drupal\Core\Url;
use GuzzleHttp\Client;
use GuzzleHttp\Exception\RequestException;

define('HUBSPOT_CLIENT_ID', '734f89bf-1b88-11e1-829a-3b413536dd4c');
define('HUBSPOT_SCOPE', 'leads-rw contacts-rw offline');

/**
 * Returns the default value for the given arguments.
 */
function _hubspot_default_value($nid, $hubspot_guid = NULL, $webform_field = NULL) {
  if (empty($hubspot_guid)) {
    return db_query_range("SELECT hubspot_guid FROM {hubspot} h WHERE h.nid = :nid", 0, 1, array(':nid' => $nid))->fetchField();
  }
  else {
    return db_query_range("SELECT hubspot_field FROM {hubspot} h WHERE h.nid = :nid AND h.hubspot_guid = :guid AND h.webform_field = :webform_field", 0, 1, array(
      ':nid' => $nid,
      ':guid' => $hubspot_guid,
      ':webform_field' => $webform_field,
    ))->fetchField();
  }


}

/**
 * Gets the list of forms from HubSpot via the API.
 */
function _hubspot_get_forms() {
  $access_token = \Drupal::config('hubspot.settings')->get('hubspot_access_token');

  if (empty($access_token)) {
    return array('error' => t('This site is not connected to a HubSpot Account.'));
  }

  $api = 'https://api.hubapi.com/contacts/v1/forms';
  $options = [
    'query' => ['access_token' => $access_token],
  ];
  $url = Url::fromUri($api, $options)->toString();
  try {
    $response = \Drupal::httpClient()->get($url);
    $data = (string) $response->getBody();
    return ['value' => Json::decode($data)];
  }
  catch (RequestException $e) {

  }
}
